# Generated by Django 4.2.25 on 2025-11-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('agency', 'Agency'), ('traveler', 'Traveler')], default='traveler', max_length=10),
        ),
    ]
