# Generated by Django 4.2.25 on 2025-11-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_tour_travel_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='discount_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='is_discounted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
