# Generated by Django 4.2.25 on 2025-11-06 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visarequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visa',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visas', to=settings.AUTH_USER_MODEL),
        ),
    ]
